SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d7jpontckfvc73du51fg-a:5432/testlab_hiit
SPRING_DATASOURCE_USERNAME=testlab_hiit_user
SPRING_DATASOURCE_PASSWORD=jQ5UC6PXfKcvDAdjEydMPY7LRgh861DZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}